[package]
name = "pokemon-icat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
csv = "1.3.0"
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
